### ISSUE TITLE
Exception on authentication failure

### ISSUE THREAD

**Issue by texpert** [vassilevsky/face_control#17]
When wrong credentials are provided in `~/.stashconfig.yml`, `face-control` is throwing an exception:

```
+ face-control FRNT app 939
/var/lib/jenkins/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/face_control-0.9.0/lib/stash/pull_request/diff.rb:21:in `diffs_with_added_lines': private method `select' called for nil:NilClass (NoMethodError)
	from /var/lib/jenkins/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/face_control-0.9.0/lib/stash/pull_request/diff.rb:9:in `filenames_with_added_lines'
	from /var/lib/jenkins/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/face_control-0.9.0/lib/stash/pull_request.rb:13:in `filenames_with_added_lines'
	from /var/lib/jenkins/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/face_control-0.9.0/lib/face_control/cli.rb:27:in `check'
	from /var/lib/jenkins/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/face_control-0.9.0/lib/face_control/cli.rb:15:in `run'
	from /var/lib/jenkins/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/face_control-0.9.0/exe/face-control:5:in `<top (required)>'
	from /var/lib/jenkins/.rbenv/versions/2.3.4/bin/face-control:22:in `load'
	from /var/lib/jenkins/.rbenv/versions/2.3.4/bin/face-control:22:in `<main>'
I, [2017-09-05T12:23:23.242628 #29730]  INFO -- : Running checkers...
D, [2017-09-05T12:23:23.269745 #29730] DEBUG -- : [HTTParty] [2017-09-05 12:23:23 +0000] 401 "GET https://www.server.net/rest/api/1.0/projects/app/repos/fapp/pull-requests/939/diff?withComments=false" - 
D, [2017-09-05T12:23:23.269782 #29730] DEBUG -- : Response:
{"errors":[{"context":null,"message":"Authentication failed. Please check your credentials and try again.","exceptionName":"com.atlassian.bitbucket.auth.IncorrectPasswordAuthenticationException"}]}
+ exit 0
```

**Comment by vassilevsky** [comment]
I've added primitive server error handling. I believe this is enough. A bit ugly, but informative. Long overdue. Released in version *0.9.1*.
